databases:
  - name: feedback-db
    plan: free

services:
  # Backend
  - type: web
    name: giko-backend
    runtime: docker
    rootDir: ./backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feedback-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: giko-frontend
          property: host

  # Frontend (static web service — don't include `plan`)
  - type: web
    name: giko-frontend
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: giko-backend
          property: host
