# render.yaml - Deploy this using the "New Blueprint" feature on Render.

databases:
  - name: giko-db # The name of your database.
    plan: free

services:
  # 1. The Python Backend Service
  - type: web
    name: giko-backend
    runtime: docker
    rootDir: ./backend
    plan: free
    startCommand: "python -m app.seed && uvicorn app.main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: giko-db # This MUST match the database name above.
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: static
          name: giko-frontend # This MUST match the frontend service name below.
          property: url

  # 2. The React Frontend Service
  - type: static
    name: giko-frontend
    rootDir: ./frontend
    plan: free
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL # Use VITE_API_URL for Vite projects
        fromService:
          type: web
          name: giko-backend # This MUST match the backend service name above.
          property: url