previews: enabled
services:
  # 1. The Python Backend Service (with Auto-Seeding)
  - type: web
    name: giko-backend
    runtime: docker
    rootDir: ./backend
    plan: free
    startCommand: "python -m app.seed && uvicorn app.main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feedback-db # Must match the name of the PostgreSQL DB you create manually on Render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: static
          name: giko-frontend
          property: url

  # 2. The React Frontend Service
  - type: static
    name: giko-frontend
    rootDir: ./frontend
    plan: free
    buildCommand: npm install && npm run build
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: giko-backend
          property: url
