databases:
  - name: feedback-db
    plan: free

services:
  # Backend Service
  - type: web
    name: giko-backend
    runtime: docker
    rootDir: ./backend
    plan: free
    startCommand: "python -m app.seed && uvicorn app.main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: giko-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: giko-frontend
          property: url

  # React Frontend Service (as a web service)
  - type: web
    name: giko-frontend
    runtime: static
    rootDir: ./frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: giko-backend
          property: url
