databases:
  - name: feedback-db
    plan: free

services:
  # Backend
  - type: web
    name: giko-backend
    runtime: docker
    rootDir: ./backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feedback-db  # ← this MUST match your Render DB name exactly
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: giko-frontend
          property: host

  # Frontend
  - type: web
    name: giko-frontend
    runtime: static
    rootDir: ./frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: giko-backend
          property: host
